apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-integration-deployment
  labels:
    app: devops-integration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-integration
  template:
    metadata:
      labels:
        app: devops-integration
    spec:
      containers:
        - name: devops-integration
          image: mrakshay09/devops-integration:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: devops-integration-service
spec:
  selector:
    app: devops-integration
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
