FROM openjdk:17-jdk-slim
# Expose port used by Spring Boot
EXPOSE 8080
WORKDIR /app
# Copy the built jar from the build stage
COPY --from=build /app/target/*.jar docker-jenkins-integration.jar
# Run the app
ENTRYPOINT ["java", "-jar", "docker-jenkins-integration.jar"]
